### ISSUE TITLE
Rework File API, use nanoid instead of file id on every transaction.

### ISSUE THREAD

**Issue by shygnome** [worxid/worx#176]
## Description
Rework File API, use nanoid instead of file id on every transaction.

### To-do List
- [x] Add `name`, `media_id`, and `original_name` columns to `File` table. The `original_name` indicates its original filename, which will be submitted when the client asks for a pre-signed URL. The `media_id` is the generated id from the server. And the `name` column is the generated name from the server.
- [x] Generate `media_id` and `name` with the nanoid library. The `media_id` format is `{16 characters nanoid}`. Then, the filename format is `{media_id}.{file extension}` https://github.com/worxid/worx/blob/468b1333ac28e38c2914fe04678ab7cad8d07265/application/src/main/java/id/worx/worx/util/UrlUtils.java#L4-L20
- [x] Change get (upload) pre-signed URL API for web (GET `/media/presigned-url`) and mobile (GET `/mobile/media/presigned-url`) flow to generate the `media_id` and the `name` value. Then, return FileResponse which contains all properties of `File` entity. 
  ```json
  {
    "id": 1,
    "media_id": "abcdefghijklmnop"
    "name": "abcdefghijklmnop.xls"
    "url": "{upload pre-signed url}",
    "path": "{media path}",
    "mime_type": "{mime_type}",
    "size": "{size}"
  }
  ```
- [x] Change download pre-signed URL API for web (GET `/media/files`) and mobile (GET `/mobile/media/download-presigned-url`) parameter to use `media_id` instead of `fileId`. Then, return FileResponse which contains all properties of `File` entity.
