### ISSUE TITLE
Add `from` and `to` parameter to search API

### ISSUE THREAD

**Issue by shygnome** [worxid/worx#188]
## Description
Add `from` and `to` parameters to enable the filter function in the search API.

## To-do list
- [ ] Form Template Search API. The "from" and "to" parameters will be compared to the `created date` field.
- [ ] Submission Search API. The "from" and "to" parameters will be compared to the `submitted date` field.
- [ ] Disable the `date` filter.
