### ISSUE TITLE
User Module

### ISSUE THREAD

**Issue by shygnome** [worxid/worx#19]
## Description
User Module

## To-do List

- [x] Create User table definition, entity class, and repository class
- [x] Implement CRUD API on User entity
- [x] Implement Auth API (sign up, sign in, logout)
