### ISSUE TITLE
Add dashboard logo to user detail

### ISSUE THREAD

**Issue by shygnome** [worxid/worx#267]
## Description
Add dashboard logo to user detail.

### Todo
- [x] Add new column `dashboard_logo` to `User` table. The column type is `Long` / `bigint` and a foreign key to `File` table (file id).
- [x] Add `dashboard_logo` (Long) to update user details.
- [x] Implement update user details with `dashboard_logo`. It should verify that the file sent is already uploaded or exists in both the database (SQL) and the storage (minio/s3).

**Comment by dwiky-valid** [comment]
untuk point 3, apakah harus apa pengecekan isObjectExist di minio/s3 ketika update `dashboard_logo `?
