### ISSUE TITLE
New Form Field Type: Barcode

### ISSUE THREAD

**Issue by shygnome** [worxid/worx#281]
## Description
New form field type `Barcode`.

### Specification

JSON Field
```json
{
    "id": "field-id",
    "label": "Barcode Question",
    "description": "Barcode Question",
    "type": "barcode",
    "required": false,
    "barcode_type": "1d",
    "allow_manual_override": true
}
```

Field explained:
- `barcode_type`: Restrict to 1D barcodes only. The available value is "1d". If not restricted, omit the field from the JSON.
- `allow_manual_override`: User can manually override. Boolean value (`true`/`false`). If not included, it's assumed this field is set to false.

JSON Value
```json
{
    "type": "barcode",
    "value": "barcode scan result"
}
```

## To-do
- [ ] Create `BarcodeField.java`
- [ ] Create `BarcodeValue.java`
- [ ] Update validate method
- [ ] Update export method
