### ISSUE TITLE
New Form Field Type: Sketch

### ISSUE THREAD

**Issue by shygnome** [worxid/worx#282]
## Description
New form field type `Sketch`.

### Specification

JSON Field
```json
{
    "id": "field-id",
    "label": "Sketch Question",
    "description": "Sketch Question",
    "type": "sketch",
    "required": false
}
```

JSON Value
```json
{
    "type": "sketch",
    "file_id": 815
}
```

## To-do
- [ ] Create `SketchField.java`
- [ ] Create `SketchValue.java`
- [ ] Update validate method
- [ ] Update export method
