### ISSUE TITLE
New Form Field Type: Yes/No

### ISSUE THREAD

**Issue by shygnome** [worxid/worx#295]
## Description
New form field type `Yes/No`.

### Specification

JSON Field
```json
{
    "id": "yesno-id",
    "label": "Yes/No Question",
    "description": "Yes/No Question",
    "type": "boolean",
    "required": false
}
```

JSON Value
```json
{
    "type": "boolean",
    "value": true
}
```

## To-do
- [ ] Create `BooleanField.java`
- [ ] Create `BooleanValue.java`
- [ ] Update validate method
- [ ] Update export method
