### ISSUE TITLE
New Form Field Type: Integer

### ISSUE THREAD

**Issue by shygnome** [worxid/worx#296]
## Description
New form field type `Integer`.

### Specification

JSON Field
```json
{
    "id": "integer-id",
    "label": "Integer Question",
    "description": "Integer Question",
    "type": "integer",
    "required": false
}
```

JSON Value
```json
{
    "type": "integer",
    "value": 12
}
```

## To-do
- [ ] Create `IntegerField.java`
- [ ] Create `IntegerValue.java`
- [ ] Update validate method
- [ ] Update export method
