### ISSUE TITLE
Error Handling Module

### ISSUE THREAD

**Issue by shygnome** [worxid/worx#42]
## Description
Error Handling Module

## To-do List

- [x] Create error handling classes, including Worx error code enum definition, error handler class, and error response class.
- [x] List current available error code enum.
- [x] Create error response builder.
- [x] Create validation error class for Form validation.
